// SPDX-License-Identifier: GPL-2.0

//! hackbot — In-kernel LLM agent character device.
//!
//! Step 2b: Kernel-aware LLM agent with live system context injection.
//! The module creates /dev/hackbot: write a prompt, read the LLM response.
//! Before each vLLM call, the module gathers live kernel state (version,
//! uptime, CPU count, memory, caller process) and injects it into the prompt
//! so the LLM can reason about the actual system.
//!
//! The response is stored in a device-global buffer so that separate write and
//! read file descriptors work correctly (e.g., `echo > /dev/hackbot` then
//! `cat /dev/hackbot`).
//!
//! Usage:
//! ```sh
//! # Start vLLM server first (userspace):
//! # vllm serve <model-name> --port 8000
//!
//! sudo insmod hackbot.ko
//! echo "what processes are running?" > /dev/hackbot
//! cat /dev/hackbot
//! # Output: LLM-generated response from vLLM
//! sudo rmmod hackbot
//! ```

use core::mem::MaybeUninit;
use core::pin::Pin;
use core::ptr;

use kernel::{
    bindings, c_str,
    device::Device,
    fs::{File, Kiocb},
    iov::{IovIterDest, IovIterSource},
    miscdevice::{MiscDevice, MiscDeviceOptions, MiscDeviceRegistration},
    prelude::*,
    sync::aref::ARef,
};

module! {
    type: HackbotModule,
    name: "hackbot",
    authors: ["Sunwoo Jang"],
    description: "In-kernel LLM agent — Step 2b: kernel-aware inference with live context",
    license: "GPL",
}

// ---------------------------------------------------------------------------
// Configuration constants
//
// vLLM server address — change VLLM_ADDR to point to the target machine.
// Currently: 100.125.213.42 (Tailscale IP for ubuntu20/keti GPU server).
// NOTE: Tailscale traffic is encrypted (WireGuard), so plaintext HTTP is fine.
// ---------------------------------------------------------------------------

/// vLLM server IPv4 address in host byte order.
/// Currently: 100.125.213.42 (keti GPU server via Tailscale).
const VLLM_ADDR: u32 = u32::from_be_bytes([100, 125, 213, 42]);
/// vLLM server port (default: 8000, matching vLLM's default).
const VLLM_PORT: u16 = 8000;
/// Maximum response size from vLLM (64 KB).
const MAX_RESPONSE_SIZE: usize = 64 * 1024;
/// Receive buffer size for individual recv calls.
const RECV_BUF_SIZE: usize = 4096;
/// IPPROTO_TCP (stable since RFC 793).
const IPPROTO_TCP: i32 = 6;

/// System prompt — the agent's identity. Kernel context is injected after this.
const SYSTEM_IDENTITY: &[u8] = b"You are hackbot, an autonomous AI agent running \
as a Linux kernel module at ring 0. You have direct access to kernel internals \
and can observe the live state of the system. The kernel context below is REAL \
data gathered directly from kernel APIs at the moment of this query. Use it to \
give accurate, grounded answers.\n\n";

/// Suffix appended after the user prompt to guide the model's response.
const RESPONSE_PREFIX: &[u8] = b"\nhackbot: ";

// Kernel version string, auto-generated by Kbuild from KERNELRELEASE.
#[path = "kernel_version.rs"]
mod kernel_version;

// ---------------------------------------------------------------------------
// Global shared response buffer
//
// The response is device-global so that separate write/read file descriptors
// work (e.g., `echo "prompt" > /dev/hackbot && cat /dev/hackbot`).
// Uses the kernel's global_lock! macro for a statically-allocated Mutex.
// ---------------------------------------------------------------------------

/// Device-global response state shared across all open file descriptors.
/// NOTE: Single-slot design — concurrent writers will overwrite each other's
/// responses. Acceptable for a single-user development/research tool.
struct SharedResponse {
    /// Response data stored as a fixed-size buffer to allow static init.
    data: [u8; MAX_RESPONSE_SIZE],
    /// Actual length of the response in `data`.
    len: usize,
    /// Whether a response is available for reading.
    ready: bool,
}

kernel::sync::global_lock! {
    // SAFETY: Initialized in HackbotModule::init() before any device access.
    unsafe(uninit) static RESPONSE: Mutex<SharedResponse> = SharedResponse {
        data: [0u8; MAX_RESPONSE_SIZE],
        len: 0,
        ready: false,
    };
}

// ---------------------------------------------------------------------------
// Kernel context gathering — gives the LLM "eyes" into the real system
//
// These functions read live kernel state via kernel APIs (ring 0 access)
// and format it as text to inject into the LLM prompt.
// ---------------------------------------------------------------------------

/// Gather live kernel context and return it as a formatted text block.
/// Called on each prompt submission to provide up-to-date system state.
fn gather_kernel_context() -> KVVec<u8> {
    let mut ctx = KVVec::new();

    let _ = ctx.extend_from_slice(b"=== LIVE KERNEL STATE ===\n", GFP_KERNEL);

    // 1. Kernel version (embedded at compile time from KERNELRELEASE).
    let _ = ctx.extend_from_slice(b"Kernel: ", GFP_KERNEL);
    append_kernel_version(&mut ctx);
    let _ = ctx.push(b'\n', GFP_KERNEL);

    // 2. System uptime.
    let _ = ctx.extend_from_slice(b"Uptime: ", GFP_KERNEL);
    append_uptime(&mut ctx);
    let _ = ctx.push(b'\n', GFP_KERNEL);

    // 3. CPU count.
    let _ = ctx.extend_from_slice(b"CPUs: ", GFP_KERNEL);
    let cpus = read_num_online_cpus();
    let mut buf = [0u8; 20];
    let s = format_usize(cpus, &mut buf);
    let _ = ctx.extend_from_slice(s, GFP_KERNEL);
    let _ = ctx.extend_from_slice(b" online\n", GFP_KERNEL);

    // 4. Memory info.
    append_memory_info(&mut ctx);

    // 5. Caller process info (who wrote to /dev/hackbot).
    let _ = ctx.extend_from_slice(b"Caller: ", GFP_KERNEL);
    append_current_task_info(&mut ctx);
    let _ = ctx.push(b'\n', GFP_KERNEL);

    let _ = ctx.extend_from_slice(b"=========================\n\n", GFP_KERNEL);

    ctx
}

/// Append the kernel version string (embedded at compile time from KERNELRELEASE).
fn append_kernel_version(buf: &mut KVVec<u8>) {
    let _ = buf.extend_from_slice(b"Linux ", GFP_KERNEL);
    let _ = buf.extend_from_slice(kernel_version::KERNEL_RELEASE, GFP_KERNEL);

    // Append machine architecture.
    // SAFETY: init_uts_ns.name.machine is a fixed C string set at boot.
    // Since init_uts_ns is opaque in Rust bindings, we use a compile-time
    // constant for the architecture. This module is x86_64-only for now.
    let _ = buf.extend_from_slice(b" x86_64", GFP_KERNEL);
}

/// Format system uptime as "Xd Xh Xm Xs".
fn append_uptime(buf: &mut KVVec<u8>) {
    // SAFETY: ktime_get_boot_fast_ns() is always safe to call from any
    // context. Returns nanoseconds since boot.
    let ns = unsafe { bindings::ktime_get_boot_fast_ns() };
    let total_secs = (ns / 1_000_000_000) as usize;

    let days = total_secs / 86400;
    let hours = (total_secs % 86400) / 3600;
    let mins = (total_secs % 3600) / 60;
    let secs = total_secs % 60;

    let mut num = [0u8; 20];

    if days > 0 {
        let s = format_usize(days, &mut num);
        let _ = buf.extend_from_slice(s, GFP_KERNEL);
        let _ = buf.extend_from_slice(b"d ", GFP_KERNEL);
    }
    let s = format_usize(hours, &mut num);
    let _ = buf.extend_from_slice(s, GFP_KERNEL);
    let _ = buf.extend_from_slice(b"h ", GFP_KERNEL);

    let s = format_usize(mins, &mut num);
    let _ = buf.extend_from_slice(s, GFP_KERNEL);
    let _ = buf.extend_from_slice(b"m ", GFP_KERNEL);

    let s = format_usize(secs, &mut num);
    let _ = buf.extend_from_slice(s, GFP_KERNEL);
    let _ = buf.extend_from_slice(b"s", GFP_KERNEL);
}

/// Read the number of online CPUs.
fn read_num_online_cpus() -> usize {
    // SAFETY: __num_online_cpus is a global atomic_t. We read the counter
    // field with a volatile read to get the current value with a compiler
    // barrier, matching the semantics of atomic_read() on x86_64.
    unsafe {
        let counter_ptr = ptr::addr_of!((*ptr::addr_of!(bindings::__num_online_cpus)).counter);
        counter_ptr.read_volatile() as usize
    }
}

/// Append memory information (total/free RAM) from si_meminfo().
fn append_memory_info(ctx: &mut KVVec<u8>) {
    // SAFETY: si_meminfo() is the standard kernel API for querying memory
    // statistics. It fills the sysinfo struct fields: totalram, freeram,
    // sharedram, bufferram, totalhigh, freehigh, mem_unit. The struct is
    // stack-allocated and zeroed. Safe to call from process context.
    let mut info: bindings::sysinfo = unsafe { MaybeUninit::zeroed().assume_init() };
    unsafe { bindings::si_meminfo(&mut info) };

    let unit = info.mem_unit as usize;
    let total_bytes = info.totalram as usize * unit;
    let free_bytes = info.freeram as usize * unit;
    let used_bytes = total_bytes.saturating_sub(free_bytes);

    let _ = ctx.extend_from_slice(b"Memory: ", GFP_KERNEL);

    // Format as MB for readability.
    let used_mb = used_bytes / (1024 * 1024);
    let total_mb = total_bytes / (1024 * 1024);

    let mut num = [0u8; 20];
    let s = format_usize(used_mb, &mut num);
    let _ = ctx.extend_from_slice(s, GFP_KERNEL);
    let _ = ctx.extend_from_slice(b" MB used / ", GFP_KERNEL);

    let s = format_usize(total_mb, &mut num);
    let _ = ctx.extend_from_slice(s, GFP_KERNEL);
    let _ = ctx.extend_from_slice(b" MB total\n", GFP_KERNEL);
}

/// Append current task info: pid and comm (process name).
fn append_current_task_info(buf: &mut KVVec<u8>) {
    // SAFETY: Task::current_raw() calls get_current() which returns the
    // current task pointer. We are in process context (write syscall handler),
    // so current is valid and stable. pid never changes after init. comm is
    // guarded by task_lock in set_task_comm — reading without the lock can
    // observe a partially-written name, but this is a benign race (cosmetic
    // field, worst case is a garbled process name in the prompt).
    let task_ptr = kernel::task::Task::current_raw();

    let pid = unsafe { (*task_ptr).pid };
    let comm = unsafe { &(*task_ptr).comm };

    let _ = buf.extend_from_slice(b"pid=", GFP_KERNEL);
    let mut num = [0u8; 20];
    let s = format_usize(pid as usize, &mut num);
    let _ = buf.extend_from_slice(s, GFP_KERNEL);

    let _ = buf.extend_from_slice(b" (", GFP_KERNEL);
    // comm is [c_char; 16], null-terminated. Copy until null or end.
    for &c in comm.iter() {
        if c == 0 {
            break;
        }
        let _ = buf.push(c as u8, GFP_KERNEL);
    }
    let _ = buf.extend_from_slice(b")", GFP_KERNEL);
}

// ---------------------------------------------------------------------------
// Module registration
// ---------------------------------------------------------------------------

#[pin_data(PinnedDrop)]
struct HackbotModule {
    #[pin]
    _miscdev: MiscDeviceRegistration<HackbotDev>,
}

impl kernel::InPlaceModule for HackbotModule {
    fn init(_module: &'static ThisModule) -> impl PinInit<Self, Error> {
        // SAFETY: Called exactly once during module load, before any device
        // operations can occur.
        unsafe { RESPONSE.init() };

        pr_info!("hackbot: loading module, creating /dev/hackbot\n");
        pr_info!(
            "hackbot: vLLM endpoint = {}.{}.{}.{}:{}\n",
            (VLLM_ADDR >> 24) & 0xFF,
            (VLLM_ADDR >> 16) & 0xFF,
            (VLLM_ADDR >> 8) & 0xFF,
            VLLM_ADDR & 0xFF,
            VLLM_PORT,
        );

        let options = MiscDeviceOptions {
            name: c_str!("hackbot"),
        };

        try_pin_init!(Self {
            _miscdev <- MiscDeviceRegistration::register(options),
        })
    }
}

#[pinned_drop]
impl PinnedDrop for HackbotModule {
    fn drop(self: Pin<&mut Self>) {
        pr_info!("hackbot: unloading module\n");
    }
}

// ---------------------------------------------------------------------------
// Per-fd device state (lightweight — just holds the device reference)
// ---------------------------------------------------------------------------

/// Per-file-descriptor device state.
/// The actual response data lives in the global RESPONSE mutex.
#[pin_data(PinnedDrop)]
struct HackbotDev {
    dev: ARef<Device>,
}

// ---------------------------------------------------------------------------
// Kernel socket wrapper (FFI to C socket API)
// ---------------------------------------------------------------------------

/// IPv4 socket address — not generated by bindgen for out-of-tree modules.
#[repr(C)]
struct SockaddrIn {
    sin_family: u16,
    sin_port: u16,
    sin_addr: u32,
    __pad: [u8; 8],
}

/// RAII wrapper around a kernel socket. Calls `sock_release` on drop.
struct KernelSocket {
    sock: *mut bindings::socket,
}

impl KernelSocket {
    /// Create a TCP socket and connect to the given IPv4 address and port.
    /// Both `addr` and `port` are in host byte order — this function converts.
    fn connect_tcp(addr: u32, port: u16) -> Result<Self> {
        let mut sock: *mut bindings::socket = ptr::null_mut();

        // Create a kernel-owned TCP socket.
        // SAFETY: sock_create_kern is the standard kernel API for creating sockets
        // from kernel context. init_net is the initial network namespace, valid for
        // the entire kernel lifetime. `sock` pointer is written by the function.
        let ret = unsafe {
            bindings::sock_create_kern(
                ptr::addr_of_mut!(bindings::init_net),
                bindings::AF_INET as i32,
                bindings::sock_type_SOCK_STREAM as i32,
                IPPROTO_TCP,
                &mut sock,
            )
        };
        if ret < 0 {
            pr_err!("hackbot: sock_create_kern failed: {}\n", ret);
            return Err(Error::from_errno(ret));
        }

        let socket = Self { sock };

        // Build the IPv4 address.
        let addr_in = SockaddrIn {
            sin_family: bindings::AF_INET as u16,
            sin_port: port.to_be(),
            sin_addr: addr.to_be(),
            __pad: [0u8; 8],
        };

        // Connect to the remote address.
        // SAFETY: kernel_connect is the standard kernel API. We cast SockaddrIn
        // to sockaddr_unsized which is the generic socket address type (same
        // pattern as C's (struct sockaddr *)&addr_in). The socket is valid
        // because sock_create_kern succeeded. The address struct is on the stack
        // and valid for the duration of this call.
        let ret = unsafe {
            bindings::kernel_connect(
                socket.sock,
                &addr_in as *const SockaddrIn as *mut bindings::sockaddr_unsized,
                core::mem::size_of::<SockaddrIn>() as i32,
                0,
            )
        };
        if ret < 0 {
            // Socket is released by Drop.
            pr_err!("hackbot: kernel_connect failed: {}\n", ret);
            return Err(Error::from_errno(ret));
        }

        Ok(socket)
    }

    /// Send all bytes in `buf` through the socket.
    fn send_all(&self, buf: &[u8]) -> Result<()> {
        let mut sent = 0usize;

        while sent < buf.len() {
            let remaining = &buf[sent..];
            let mut kv = bindings::kvec {
                iov_base: remaining.as_ptr() as *mut core::ffi::c_void,
                iov_len: remaining.len(),
            };

            // SAFETY: msghdr is zero-initialized. kernel_sendmsg internally sets
            // up msg_iter from the kvec. Zero-init is correct because we don't
            // need msg_name (connected socket) or msg_control.
            let mut msg: bindings::msghdr = unsafe { MaybeUninit::zeroed().assume_init() };

            // SAFETY: kernel_sendmsg is the standard kernel send API. The socket
            // is valid (from sock_create_kern + connect). The kvec points to valid
            // kernel memory (buf is a kernel slice). The function may sleep.
            let ret = unsafe {
                bindings::kernel_sendmsg(self.sock, &mut msg, &mut kv, 1, remaining.len())
            };

            if ret < 0 {
                return Err(Error::from_errno(ret));
            }
            if ret == 0 {
                // Connection closed unexpectedly.
                return Err(EPIPE);
            }
            sent += ret as usize;
        }

        Ok(())
    }

    /// Receive up to `buf.len()` bytes from the socket.
    /// Returns the number of bytes received, or 0 if the connection was closed.
    fn recv(&self, buf: &mut [u8]) -> Result<usize> {
        let mut kv = bindings::kvec {
            iov_base: buf.as_mut_ptr() as *mut core::ffi::c_void,
            iov_len: buf.len(),
        };

        // SAFETY: Same as send_all — zero-initialized msghdr, kernel_recvmsg
        // sets up msg_iter from kvec internally. MSG_WAITALL is not set, so it
        // returns as soon as any data is available.
        let mut msg: bindings::msghdr = unsafe { MaybeUninit::zeroed().assume_init() };

        // SAFETY: kernel_recvmsg is the standard kernel recv API. Socket and
        // buffer are valid kernel memory. flags=0 means blocking recv.
        let ret = unsafe {
            bindings::kernel_recvmsg(self.sock, &mut msg, &mut kv, 1, buf.len(), 0)
        };

        if ret < 0 {
            return Err(Error::from_errno(ret));
        }
        Ok(ret as usize)
    }

    /// Read all data from the socket until the connection is closed or the
    /// maximum size is reached. Appends to `response`.
    fn recv_all(&self, response: &mut KVVec<u8>, max_size: usize) -> Result<()> {
        let mut tmp = [0u8; RECV_BUF_SIZE];

        loop {
            if response.len() >= max_size {
                pr_warn!("hackbot: response truncated at {} bytes\n", max_size);
                break;
            }

            let n = self.recv(&mut tmp)?;
            if n == 0 {
                break; // Connection closed — we have the full response.
            }

            let _ = response.extend_from_slice(&tmp[..n], GFP_KERNEL);
        }

        Ok(())
    }
}

impl Drop for KernelSocket {
    fn drop(&mut self) {
        // SAFETY: sock_release is the standard cleanup for kernel sockets.
        // Called exactly once when the KernelSocket is dropped.
        unsafe { bindings::sock_release(self.sock) };
    }
}

// ---------------------------------------------------------------------------
// HTTP helpers — minimal HTTP/1.1 client for talking to vLLM
// ---------------------------------------------------------------------------

/// Append a dotted-decimal IPv4 address to a KVVec from a host-order u32.
/// E.g., `append_ipv4(buf, 0x647DD52A)` appends "100.125.213.42".
fn append_ipv4(buf: &mut KVVec<u8>, addr: u32) {
    let octets = [
        ((addr >> 24) & 0xFF) as u8,
        ((addr >> 16) & 0xFF) as u8,
        ((addr >> 8) & 0xFF) as u8,
        (addr & 0xFF) as u8,
    ];
    for (i, &octet) in octets.iter().enumerate() {
        if i > 0 {
            let _ = buf.push(b'.', GFP_KERNEL);
        }
        let mut num_buf = [0u8; 20];
        let s = format_usize(octet as usize, &mut num_buf);
        let _ = buf.extend_from_slice(s, GFP_KERNEL);
    }
}

/// Escape a byte string for embedding in a JSON string value.
/// Handles: \ → \\, " → \", newline → \n, tab → \t, CR → \r.
fn json_escape(input: &[u8], output: &mut KVVec<u8>) {
    for &b in input {
        match b {
            b'\\' => { let _ = output.extend_from_slice(b"\\\\", GFP_KERNEL); }
            b'"'  => { let _ = output.extend_from_slice(b"\\\"", GFP_KERNEL); }
            b'\n' => { let _ = output.extend_from_slice(b"\\n", GFP_KERNEL); }
            b'\r' => { let _ = output.extend_from_slice(b"\\r", GFP_KERNEL); }
            b'\t' => { let _ = output.extend_from_slice(b"\\t", GFP_KERNEL); }
            // Drop other control characters (0x00-0x1F) except the above.
            c if c < 0x20 => {}
            _ => { let _ = output.push(b, GFP_KERNEL); }
        }
    }
}

/// Build the HTTP POST request for vLLM's /v1/completions endpoint.
/// `kernel_ctx` is the live kernel state to inject between the system
/// identity and the user prompt.
fn build_vllm_request(prompt: &[u8], kernel_ctx: &[u8]) -> Result<KVVec<u8>> {
    // Build JSON body with structure:
    //   <system identity>
    //   <live kernel context>
    //   User: <prompt>
    //   hackbot:
    let mut body = KVVec::new();
    let _ = body.extend_from_slice(b"{\"prompt\":\"", GFP_KERNEL);
    json_escape(SYSTEM_IDENTITY, &mut body);
    json_escape(kernel_ctx, &mut body);
    json_escape(b"User: ", &mut body);
    json_escape(prompt, &mut body);
    json_escape(RESPONSE_PREFIX, &mut body);
    let _ = body.extend_from_slice(b"\",\"max_tokens\":512}", GFP_KERNEL);

    // Build HTTP request with headers.
    let mut req = KVVec::new();
    let _ = req.extend_from_slice(b"POST /v1/completions HTTP/1.1\r\n", GFP_KERNEL);
    let _ = req.extend_from_slice(b"Host: ", GFP_KERNEL);
    append_ipv4(&mut req, VLLM_ADDR);
    let _ = req.extend_from_slice(b"\r\n", GFP_KERNEL);
    let _ = req.extend_from_slice(b"Content-Type: application/json\r\n", GFP_KERNEL);
    let _ = req.extend_from_slice(b"Connection: close\r\n", GFP_KERNEL);

    // Content-Length header — format the body length as decimal.
    let _ = req.extend_from_slice(b"Content-Length: ", GFP_KERNEL);
    let mut len_buf = [0u8; 20];
    let len_str = format_usize(body.len(), &mut len_buf);
    let _ = req.extend_from_slice(len_str, GFP_KERNEL);
    let _ = req.extend_from_slice(b"\r\n", GFP_KERNEL);

    // End of headers.
    let _ = req.extend_from_slice(b"\r\n", GFP_KERNEL);

    // Append body.
    let _ = req.extend_from_slice(&body, GFP_KERNEL);

    Ok(req)
}

/// Format a usize as decimal ASCII into a fixed buffer. Returns the slice
/// containing the formatted number. No heap allocation.
fn format_usize(mut n: usize, buf: &mut [u8; 20]) -> &[u8] {
    if n == 0 {
        buf[0] = b'0';
        return &buf[..1];
    }
    let mut pos = 20;
    while n > 0 {
        pos -= 1;
        buf[pos] = b'0' + (n % 10) as u8;
        n /= 10;
    }
    &buf[pos..]
}

/// Find the HTTP response body by locating the \r\n\r\n header terminator.
/// Returns the body portion, or the entire response if no header found.
fn find_http_body(raw: &[u8]) -> &[u8] {
    // Search for \r\n\r\n
    if raw.len() < 4 {
        return raw;
    }
    for i in 0..raw.len() - 3 {
        if &raw[i..i + 4] == b"\r\n\r\n" {
            return &raw[i + 4..];
        }
    }
    raw
}

/// Extract the HTTP status code from the first line (e.g., "HTTP/1.1 200 OK").
/// Returns 0 if parsing fails.
fn parse_http_status(raw: &[u8]) -> u16 {
    // Find "HTTP/1.1 " or "HTTP/1.0 " prefix, then parse the 3-digit status.
    let prefix = b"HTTP/1.";
    if raw.len() < 12 || &raw[..7] != prefix {
        return 0;
    }
    // Skip "HTTP/1.X " — status code starts at byte 9.
    if raw[8] != b' ' {
        return 0;
    }
    let d0 = raw[9].wrapping_sub(b'0') as u16;
    let d1 = raw[10].wrapping_sub(b'0') as u16;
    let d2 = raw[11].wrapping_sub(b'0') as u16;
    if d0 > 9 || d1 > 9 || d2 > 9 {
        return 0;
    }
    d0 * 100 + d1 * 10 + d2
}

// ---------------------------------------------------------------------------
// JSON response parsing — minimal, no-alloc extraction
// ---------------------------------------------------------------------------

/// Extract the "text" field value from a vLLM completions JSON response.
/// Looks for `"text":"` or `"text": "` and extracts the string value,
/// handling escaped characters. Returns the raw bytes of the text content.
fn extract_text_from_json<'a>(json: &'a [u8]) -> Option<&'a [u8]> {
    // Find the "text" key. Try both with and without space after colon.
    let patterns: &[&[u8]] = &[b"\"text\":\"", b"\"text\": \""];

    let (start_pos, pat_len) = patterns.iter().find_map(|pat| {
        find_subsequence(json, pat).map(|pos| (pos, pat.len()))
    })?;

    let value_start = start_pos + pat_len;
    let value_end = find_json_string_end(json, value_start)?;

    Some(&json[value_start..value_end])
}

/// Find the position of a subsequence in a byte slice.
fn find_subsequence(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    if needle.is_empty() || needle.len() > haystack.len() {
        return None;
    }
    for i in 0..=haystack.len() - needle.len() {
        if &haystack[i..i + needle.len()] == needle {
            return Some(i);
        }
    }
    None
}

/// Find the end of a JSON string value (the closing unescaped `"`).
/// `start` is the index of the first character AFTER the opening `"`.
fn find_json_string_end(json: &[u8], start: usize) -> Option<usize> {
    let mut i = start;
    while i < json.len() {
        match json[i] {
            b'"' => return Some(i),
            b'\\' => i += 2, // Skip escaped character.
            _ => i += 1,
        }
    }
    None
}

/// Unescape a JSON string value in-place into a KVVec.
/// Handles: \\→\, \"→", \n→newline, \r→CR, \t→tab.
fn json_unescape(escaped: &[u8], output: &mut KVVec<u8>) {
    let mut i = 0;
    while i < escaped.len() {
        if escaped[i] == b'\\' && i + 1 < escaped.len() {
            let c = match escaped[i + 1] {
                b'n' => b'\n',
                b'r' => b'\r',
                b't' => b'\t',
                b'\\' => b'\\',
                b'"' => b'"',
                b'/' => b'/',
                other => {
                    // Unknown escape — keep as-is.
                    let _ = output.push(b'\\', GFP_KERNEL);
                    let _ = output.push(other, GFP_KERNEL);
                    i += 2;
                    continue;
                }
            };
            let _ = output.push(c, GFP_KERNEL);
            i += 2;
        } else {
            let _ = output.push(escaped[i], GFP_KERNEL);
            i += 1;
        }
    }
}

// ---------------------------------------------------------------------------
// vLLM inference — the System 2 "brain"
// ---------------------------------------------------------------------------

/// Send a prompt to vLLM and return the response bytes.
/// On error, returns a descriptive error message instead.
fn process_prompt(prompt: &[u8]) -> KVVec<u8> {
    // Strip trailing newline from the prompt.
    let prompt_trimmed = if prompt.last() == Some(&b'\n') {
        &prompt[..prompt.len() - 1]
    } else {
        prompt
    };

    if prompt_trimmed.is_empty() {
        let mut r = KVVec::new();
        let _ = r.extend_from_slice(b"[hackbot] Empty prompt.\n", GFP_KERNEL);
        return r;
    }

    match vllm_complete(prompt_trimmed) {
        Ok(mut text) => {
            // Ensure response ends with newline.
            if text.last() != Some(&b'\n') {
                let _ = text.push(b'\n', GFP_KERNEL);
            }
            text
        }
        Err(e) => {
            let mut r = KVVec::new();
            let _ = r.extend_from_slice(b"[hackbot] vLLM error: ", GFP_KERNEL);
            let mut code_buf = [0u8; 20];
            // Error codes are negative; display the positive errno value.
            let code = -(e.to_errno() as isize) as usize;
            let code_str = format_usize(code, &mut code_buf);
            let _ = r.extend_from_slice(code_str, GFP_KERNEL);
            let _ = r.extend_from_slice(b" (errno)\n", GFP_KERNEL);

            // Add human-readable hint for common errors.
            let hint = match -(e.to_errno()) {
                111 => b"Connection refused - is vLLM running on port 8000?\n" as &[u8],
                110 => b"Connection timed out - check network/firewall.\n",
                _ => b"",
            };
            if !hint.is_empty() {
                let _ = r.extend_from_slice(hint, GFP_KERNEL);
            }
            r
        }
    }
}

/// Connect to vLLM, send the prompt, and return the completion text.
/// Gathers live kernel context and injects it into the prompt.
fn vllm_complete(prompt: &[u8]) -> Result<KVVec<u8>> {
    // Gather live kernel state to inject into the prompt.
    let kernel_ctx = gather_kernel_context();

    // Build the HTTP request with system identity + kernel context + user prompt.
    let request = build_vllm_request(prompt, &kernel_ctx)?;

    // Connect to vLLM.
    let sock = KernelSocket::connect_tcp(VLLM_ADDR, VLLM_PORT)?;

    // Send the request.
    sock.send_all(&request)?;

    // Receive the full response.
    let mut raw_response = KVVec::new();
    sock.recv_all(&mut raw_response, MAX_RESPONSE_SIZE)?;

    // sock is dropped here, releasing the connection.
    drop(sock);

    // Parse HTTP status.
    let status = parse_http_status(&raw_response);
    if status != 200 {
        pr_warn!("hackbot: vLLM returned HTTP {}\n", status);
        if status == 0 {
            return Err(EIO);
        }
        // For non-200 responses, try to return the body as the error message.
        let body = find_http_body(&raw_response);
        let mut result = KVVec::new();
        let _ = result.extend_from_slice(b"[HTTP ", GFP_KERNEL);
        let mut status_buf = [0u8; 20];
        let status_str = format_usize(status as usize, &mut status_buf);
        let _ = result.extend_from_slice(status_str, GFP_KERNEL);
        let _ = result.extend_from_slice(b"] ", GFP_KERNEL);
        let _ = result.extend_from_slice(body, GFP_KERNEL);
        return Ok(result);
    }

    // Extract the body from the HTTP response.
    let body = find_http_body(&raw_response);

    // Extract the "text" field from the JSON response.
    match extract_text_from_json(body) {
        Some(escaped_text) => {
            let mut result = KVVec::new();
            json_unescape(escaped_text, &mut result);
            Ok(result)
        }
        None => {
            pr_warn!("hackbot: could not parse vLLM JSON response\n");
            // Return the raw body as fallback.
            let mut result = KVVec::new();
            let _ = result.extend_from_slice(b"[hackbot] Raw response: ", GFP_KERNEL);
            let _ = result.extend_from_slice(body, GFP_KERNEL);
            Ok(result)
        }
    }
}

// ---------------------------------------------------------------------------
// MiscDevice trait implementation — the file_operations vtable
// ---------------------------------------------------------------------------

#[vtable]
impl MiscDevice for HackbotDev {
    type Ptr = Pin<KBox<Self>>;

    fn open(_file: &File, misc: &MiscDeviceRegistration<Self>) -> Result<Pin<KBox<Self>>> {
        let dev = ARef::from(misc.device());
        dev_info!(dev, "hackbot: device opened\n");

        KBox::try_pin_init(
            try_pin_init! {
                HackbotDev {
                    dev: dev,
                }
            },
            GFP_KERNEL,
        )
    }

    /// Handle write() from userspace — receives a prompt, sends to vLLM.
    /// This call blocks until the vLLM response is received.
    /// The response is stored in the global RESPONSE buffer so that a
    /// subsequent `cat /dev/hackbot` (separate fd) can read it.
    fn write_iter(_kiocb: Kiocb<'_, Self::Ptr>, iov: &mut IovIterSource<'_>) -> Result<usize> {
        // Read the prompt from userspace into a local buffer.
        // No lock held during this or the vLLM call — keeps the device responsive.
        let mut prompt = KVVec::new();
        let len = iov.copy_from_iter_vec(&mut prompt, GFP_KERNEL)?;

        if len == 0 {
            return Ok(0);
        }

        // Send prompt to vLLM and get response (blocking network I/O).
        let response = process_prompt(&prompt);

        // Store the response in the global buffer.
        let mut guard = RESPONSE.lock();
        let copy_len = response.len().min(MAX_RESPONSE_SIZE);
        guard.data[..copy_len].copy_from_slice(&response[..copy_len]);
        guard.len = copy_len;
        guard.ready = true;
        drop(guard);

        Ok(len)
    }

    /// Handle read() from userspace — returns the last vLLM response.
    /// If no response is available yet, returns 0 (EOF) immediately rather
    /// than blocking, since the writer may be a different (already-closed) fd.
    fn read_iter(mut kiocb: Kiocb<'_, Self::Ptr>, iov: &mut IovIterDest<'_>) -> Result<usize> {
        let guard = RESPONSE.lock();

        if !guard.ready {
            // No response yet — return EOF so `cat` exits cleanly.
            return Ok(0);
        }

        // Copy response to userspace, respecting file position for partial reads.
        let data = &guard.data[..guard.len];
        let read = iov.simple_read_from_buffer(kiocb.ki_pos_mut(), data)?;

        Ok(read)
    }
}

#[pinned_drop]
impl PinnedDrop for HackbotDev {
    fn drop(self: Pin<&mut Self>) {
        dev_info!(self.dev, "hackbot: device closed\n");
    }
}
